In [1]:
import numpy as np

In [3]:
np.ones(3)
np.zeros(3)
np.random.random(3)

array([0.41605111, 0.21975379, 0.47349541])

In [4]:
data = np.array([1, 2])
ones = np.ones(2)

In [5]:
print(data+ones)

[2. 3.]


numpy中的乘法是一种广播机制

## 索引

In [7]:
data = np.array([1,2,3])
print(data[:2])

[1 2]


## 聚合

In [8]:
print(data.max())
print(data.min())
print(data.sum())

3
1
6


当是多维数组时，如果两个矩阵的行列数相同，就可以使用运算符对矩阵进行运算。

In [10]:
data = np.array([[1,2],[3,4]])
ones = np.ones((2,2))
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [12]:
data = np.array([[1,2],[3,4],[5,6]])
ones = np.ones((1,2))  # 这种形状不同的相加，必须是一个一维的（只有一行或一列）
print(data+ones)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


## 矩阵点积
矩阵相乘使用dot()

In [15]:
data = np.array([1,2,3])
power_of_ten = np.array([[1,10],[100,1000],[10000,100000]])
data.dot(power_of_ten)

array([ 30201, 302010])

## 矩阵索引

In [21]:
data = np.array([[1,2],[3,4],[5,6]])
print(data[0,1])
print(data[1:3])
print(data[0:2,0])
print(data[1,0:2])
print(data[0:2,0:2])

2
[[3 4]
 [5 6]]
[1 3]
[3 4]
[[1 2]
 [3 4]]


## 矩阵聚合

In [22]:
data = np.array([[1,2],[3,4],[5,6]])
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [23]:
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

[[1 2]
 [3 4]
 [5 6]]
[5 6]
[2 4 6]


## 置换和变形

In [25]:
data = np.array([1,2,3,4,5,6])
print(data)
print(data.reshape(2,3))
print(data.reshape(3,2))
print(data.reshape(-1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


## 更高维度

In [26]:
print(np.ones((4,3,2)))
print(np.zeros((4,3,2)))
print(np.random.random((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[0.10264037 0.43852981]
  [0.31351202 0.38193831]
  [0.08793139 0.65289554]]

 [[0.74850911 0.83972405]
  [0.36911701 0.3907665 ]
  [0.86326465 0.30009676]]

 [[0.49616114 0.32526322]
  [0.49605381 0.50414538]
  [0.39164469 0.15634292]]

 [[0.62553319 0.21139228]
  [0.22070375 0.93866223]
  [0.51011107 0.52300815]]]
